version: '3.3'

services:

  #backend
  airbnb-suggestions:
    restart: always
    container_name: backend_suggestion
    build: ./
    working_dir: /usr/src/airbnb_suggestions
    ports:
      - "8081:8081"
    volumes:
      - ./:/usr/src/airbnb_suggestions
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
 #     - ./wait-for-it.sh:/user/src/airbnb_review/wait-for-it.sh
    depends_on:
      - db2
    links:
      - db2
    #command: ["wait-for-it.sh","db:3306","--timeout=20","--",""]
    #command: ./wait-for-it.sh db:3306 -- sh -c "npm run seed && exec node server/server.js"
    command: bash -c "wait-for-it.sh db2:3306 && npm run docker --timeout=20"


  #mysql

  db2:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: airbnb2
    #command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3307:3306'
    expose:
      - 3307
    volumes:
      - db2:/var/lib/mysql2
      - ./MYSQL/schema.sql:/docker-entrypoint-initdb.d/schema.sql


volumes:
  db2: